from __future__ import annotations

from ichingpy.enum.mixed_enum import MixEnum

# Class-level mapping for "generates", Enum does not allow for ClassVar...
GENERATE_MAPPING: dict[str, str] = {
    "WOOD": "FIRE",
    "FIRE": "EARTH",
    "EARTH": "METAL",
    "METAL": "WATER",
    "WATER": "WOOD",
}

# Pre-computed reverse mappings — avoids reconstructing on every property access
GENERATED_BY_MAPPING: dict[str, str] = {v: k for k, v in GENERATE_MAPPING.items()}

OVERCOME_MAPPING: dict[str, str] = {
    "WOOD": "EARTH",
    "FIRE": "METAL",
    "EARTH": "WATER",
    "METAL": "WOOD",
    "WATER": "FIRE",
}

# Pre-computed reverse mappings — avoids reconstructing on every property access
OVERCOME_BY_MAPPING: dict[str, str] = {v: k for k, v in OVERCOME_MAPPING.items()}


class FivePhase(MixEnum):
    """The FivePhases (五行) Enum class."""

    METAL = 1, "金"
    WOOD = 2, "木"
    WATER = 3, "水"
    FIRE = 4, "火"
    EARTH = 5, "土"

    @property
    def generates(self) -> "FivePhase":
        """Return the phase generated by this phase."""
        return FivePhase[GENERATE_MAPPING[self.name]]

    @property
    def generated_by(self) -> "FivePhase":
        """Return the phase that generates this phase (我生者)."""
        return FivePhase[GENERATED_BY_MAPPING[self.name]]

    @property
    def overcomes(self) -> "FivePhase":
        """Return the phase that overcomes this phase."""
        return FivePhase[OVERCOME_MAPPING[self.name]]

    @property
    def overcome_by(self) -> "FivePhase":
        """Return the phase that is overcome by this phase (克我者)."""
        return FivePhase[OVERCOME_BY_MAPPING[self.name]]

    def seasonal_strength(self, month_phase: FivePhase) -> "SeasonalStrength":
        """Return this phase's elemental strength for the given month phase.

        Args:
            month_phase: The dominant FivePhase of the current month.

        Returns:
            SeasonalStrength indicating 旺/相/休/囚/死.
        """
        from ichingpy.enum.seasonal_strength import SeasonalStrength

        if self == month_phase:
            return SeasonalStrength.PROSPEROUS
        if self == month_phase.generates:
            return SeasonalStrength.STRONG
        if self == month_phase.generated_by:
            return SeasonalStrength.RESTING
        if self == month_phase.overcome_by:
            return SeasonalStrength.IMPRISONED
        return SeasonalStrength.DEAD
