from ichingpy.enum.mixed_enum import MixEnum


class SeasonalStrength(MixEnum):
    """Elemental seasonal strength (旺相休囚死)."""

    PROSPEROUS = 1, "旺"   # 当令 — month's own phase
    STRONG = 2, "相"       # 得生 — generated by the month's phase
    RESTING = 3, "休"      # 休息 — generates the month's phase
    IMPRISONED = 4, "囚"   # 受制 — overcomes the month's phase
    DEAD = 5, "死"         # 无力 — overcome by the month's phase
